const STYLES = `
  body { font-family: Arial, sans-serif; padding: 24px; color: #1e293b; }
  h1 { color: #1e40af; font-size: 22px; margin-bottom: 4px; }
  .subtitle { color: #64748b; font-size: 13px; margin-bottom: 24px; }
  h2 { color: #1e293b; font-size: 16px; margin: 24px 0 8px; padding: 8px 12px;
       background: #f1f5f9; border-left: 4px solid #2563eb; border-radius: 4px; }
  h2.uncategorised { border-left-color: #f59e0b; background: #fffbeb; }
  table { width: 100%; border-collapse: collapse; margin-bottom: 8px; font-size: 13px; }
  th { background: #e2e8f0; color: #475569; padding: 7px 10px; text-align: left; font-size: 12px; text-transform: uppercase; }
  td { border-bottom: 1px solid #f1f5f9; padding: 7px 10px; vertical-align: top; }
  tr:last-child td { border-bottom: none; }
  .badge { display: inline-block; padding: 2px 8px; border-radius: 999px; font-size: 11px; font-weight: 600; }
  .badge-box { background: #dbeafe; color: #1e40af; }
  .badge-lb { background: #fee2e2; color: #991b1b; }
  .empty { color: #94a3b8; font-style: italic; font-size: 13px; padding: 8px 0; }
  .footer { margin-top: 32px; padding-top: 12px; border-top: 1px solid #e2e8f0;
            font-size: 11px; color: #94a3b8; text-align: center; }
`;

function buildItemTable(items) {
  if (items.length === 0) return '<p class="empty">No items</p>';
  let html = '<table><thead><tr><th>Item</th><th>Qty</th><th>Box #</th><th>Value</th><th>Notes</th><th>Status</th></tr></thead><tbody>';
  items.forEach(item => {
    const lb = item.leaveBehind ? '<span class="badge badge-lb">Excluded</span>' : '';
    html += `<tr>
      <td><strong>${item.name || ''}</strong></td>
      <td>${item.quantity || 1}</td>
      <td><span class="badge badge-box">${item.boxNumber || 'N/A'}</span></td>
      <td>${item.valueBand !== undefined ? item.valueBand : ''}</td>
      <td>${item.notes || ''}</td>
      <td>${lb}</td>
    </tr>`;
  });
  html += '</tbody></table>';
  return html;
}

function openPrintWindow(html, title) {
  const win = window.open('', '_blank');
  win.document.write(html);
  win.document.close();
  win.print();
}

export function exportByRoom(rooms, allItems, moveTitle) {
  const title = moveTitle || 'My Move';
  const date = new Date().toLocaleDateString();
  let html = `<html><head><title>${title} - By Room</title><style>${STYLES}</style></head><body>`;
  html += `<h1>📦 ${title} — Inventory by Room</h1><p class="subtitle">Exported on ${date}</p>`;

  let hasAnyItem = false;
  rooms.forEach(room => {
    const roomItems = allItems.filter(i => i.roomId === room.id);
    if (roomItems.length > 0) hasAnyItem = true;
    html += `<h2>${room.icon || '🛏️'} ${room.name} (${roomItems.length})</h2>`;
    html += buildItemTable(roomItems);
  });

  // Uncategorised: items with no matching room
  const roomIds = rooms.map(r => r.id);
  const uncategorised = allItems.filter(i => !i.roomId || !roomIds.includes(i.roomId));
  if (uncategorised.length > 0) {
    html += `<h2 class="uncategorised">⚠️ Uncategorised (${uncategorised.length})</h2>`;
    html += buildItemTable(uncategorised);
  }

  if (!hasAnyItem && uncategorised.length === 0) {
    html += '<p class="empty">No items found.</p>';
  }

  html += `<div class="footer">Generated by MoveMate &bull; ${title} &bull; ${date} &bull; Developed with ❤️ by skm</div>`;
  html += '</body></html>';
  openPrintWindow(html, title);
}

export function exportByBox(rooms, allItems, moveTitle) {
  const title = moveTitle || 'My Move';
  const date = new Date().toLocaleDateString();
  let html = `<html><head><title>${title} - By Box</title><style>${STYLES}</style></head><body>`;
  html += `<h1>📦 ${title} — Inventory by Box Number</h1><p class="subtitle">Exported on ${date}</p>`;

  // Group items by boxNumber
  const boxMap = {};
  allItems.forEach(item => {
    const key = (item.boxNumber && item.boxNumber.trim() !== '' && item.boxNumber.trim().toUpperCase() !== 'NA') ? item.boxNumber.trim().toUpperCase() : null;    if (key) {
      if (!boxMap[key]) boxMap[key] = [];
      boxMap[key].push(item);
    }
  });

  // Sort box keys: numeric first, then alpha
  const sortedKeys = Object.keys(boxMap).sort((a, b) => {
    const na = parseInt(a), nb = parseInt(b);
    if (!isNaN(na) && !isNaN(nb)) return na - nb;
    if (!isNaN(na)) return -1;
    if (!isNaN(nb)) return 1;
    return a.localeCompare(b);
  });

  if (sortedKeys.length > 0) {
    sortedKeys.forEach(boxKey => {
      const boxItems = boxMap[boxKey];
      html += `<h2>📦 Box ${boxKey} (${boxItems.length} item${boxItems.length !== 1 ? 's' : ''})</h2>`;
      html += buildItemTable(boxItems);
    });
  }

  // Uncategorised: items with no box number or NA
  const uncategorised = allItems.filter(i => !i.boxNumber || i.boxNumber.trim() === '' || i.boxNumber.trim().toUpperCase() === 'NA');
  if (uncategorised.length > 0) {
    html += `<h2 class="uncategorised">⚠️ Uncategorised / No Box (${uncategorised.length})</h2>`;
    html += buildItemTable(uncategorised);
  }

  if (sortedKeys.length === 0 && uncategorised.length === 0) {
    html += '<p class="empty">No items found.</p>';
  }

  html += `<div class="footer">Generated by MoveMate &bull; ${title} &bull; ${date}</div>`;
  html += '</body></html>';
  openPrintWindow(html, title);
}
 &bull; Developed with ❤️ by skm
// Keep original export as alias for backwards compat
export function exportToPDF(rooms, allItems, moveTitle) {
  exportByRoom(rooms, allItems, moveTitle);
}
